:sparkles: Select Component
rubric-dev/parte-ui pull request #113
Opened 2023-02-20 06:23 UTC by dohye1

# 제목
Select Component를 추가했습니다.
react-select를 사용해서 구현했습니다.
그래서 디자인수정이 대부분입니다.

## 내용
Input과 Dropdown 컴포넌트를 합쳐서 구현하려고했으나,
react-select자체에서 제공하는 메서드와 프롭스를 그대로 사용하는게 버그발생확률이 낮을것같아서 react-select내부 컴포넌트를 사용했습니다.

## 설계
static select와 async select의 디자인은 동일하기때문에, 하나의 컴포넌트로 만들었습니다.
type='static' | 'async'로 구분해서 사용하면됩니다.

## 디자인
디자인 리뷰를 해주시면되는데, input과 dropdown을 사용한게아니라, 따로 스타일설정을했으니 디자인을 다시 확인해주셔야 할것같아요!!

## 기타
chromatic build error가 났는데 확인해봐야할것같아요

2023-03-09 04:58 UTC, june6723 requested changes

2023-03-09 04:58 UTC, june6723 commented on src/Select/AsyncSelect.stories.tsx
> +};
```ts
const getOptionsAsync = (page: number): Promise<Option<string>[]> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(
        Array.from({ length: 30 }).map((_, index) => ({
          label: `page${page}-${index}`,
          value: `page${page}-${index}`,
          icon: index % 3 === 0 ? <ActionAddIcon size={12} /> : undefined,
        }))
      );
    }, 500);
  });
};
```
비동기 테스트는 이거 추가해서

2023-03-09 04:58 UTC, june6723 commented on src/Select/AsyncSelect.stories.tsx
> +    const OPTION = getOptions(additional.page);
`const OPTION = await getOptionsAsync(additional.page);`
이렇게해서 확실하게 테스트 가능하도록 하는걸 제안합니다!

2023-03-09 04:58 UTC, june6723 commented on src/Select/AsyncSelect.stories.tsx
> +    const OPTION = getOptions(additional.page);
여기두

2023-03-09 04:58 UTC, june6723 commented on src/Select/Select.tsx
> +        noOptionsMessage={NoOptionsMessage}
loadingMessage도 기본적으로 
![image](https://user-images.githubusercontent.com/57249866/223919400-cfe554bf-f780-4101-9597-ce318d788ad4.png)
미리 스타일링 해놓고 기본으로 두면 좋을것 같습니다

`noOptionsMessage`이나 `loadingMessage`는 주입할 수 있도록 {...props} 이전에 주입하는 걸로 순서를 변경하면 좋을것 같아요

2023-03-09 04:58 UTC, june6723 commented on src/Select/util.tsx
> +      color: '##8F95B2',
`##`
오타인거죠? 아래 2줄 더 있음

2023-03-09 04:58 UTC, june6723 commented on src/Select/Select.tsx
> +  const styles = getStyles({ isError }) as StylesConfig<Option<T>, boolean>;
```ts
import { ThemeContext } from 'styled-components';
  ...
  const themeContext = useContext(ThemeContext);
  const styles = getStyles({ isError, themeContext }) as StylesConfig<Option<T>, boolean>;
```
이렇게 theme을 가져와서 getStyles에 넘겨준 다음

2023-03-09 04:58 UTC, june6723 commented on src/Select/util.tsx
> +}): StylesConfig<Option<unknown>, boolean> => ({
여기서 theme을 받도록해서 컬러도 theme에서 가져와서 사용하면 아주 좋을것 같습니다

2023-03-09 04:58 UTC, june6723 commented on src/Select/Select.tsx
> +    </Box>
loading 상태일때 select 높이가 깨집니다
여기 로딩 아이콘 때문에 높이가 달라지는듯

2023-03-09 05:01 UTC, june6723 commented on src/Select/Select.tsx
> +  const styles = getStyles({ isError }) as StylesConfig<Option<T>, boolean>;
[정정]
아예 [useTheme](https://styled-components.com/docs/advanced#via-usetheme-custom-hook) 훅이 있네요

2023-03-09 05:04 UTC, dohye1 commented on src/Select/util.tsx
> +}): StylesConfig<Option<unknown>, boolean> => ({
네네 style폴더자체를 custom hook으로 만들어서 theme을 사용해볼게요

2023-03-09 05:21 UTC, dohye1 commented on src/Select/Select.tsx
> +        noOptionsMessage={NoOptionsMessage}
loading에 대해서는 기본 스타일이없어서 창희님한테 추가해달라고 요청하겠습니다~

2023-03-09 05:23 UTC, dohye1 commented on src/Select/Select.tsx
> +    </Box>
box에 display="flex" props 넘겨주니깐 높이가 잘 잡히네요

2023-03-14 08:29 UTC, june6723 approved these changes
LGTM

2023-03-14 08:29 UTC, june6723 commented on src/Select/useSelectStyle.tsx
> +const useSelectStyle = ({
편안~하네요 굿입니다👍

2023-03-14 08:29 UTC, merged